import { useEffect, useMemo, useRef, useState } from 'react';

const API = import.meta.env.VITE_API_URL || '/api';
const sea5 = '/WhatsApp%20Image%202026-07-13%20at%2010.38.58%20PM.jpeg';
const sea5Pool = '/WhatsApp%20Image%202026-07-13%20at%2010.38.58%20PM%20(1).jpeg';
const sea5Detail = '/WhatsApp%20Image%202026-07-13%20at%2010.38.58%20PM%20(2).jpeg';

const vehicleData = [
  { name: 'SEA 5.0', image: sea5, tagline: 'Flagship autonomous underwater vehicle', specs: { Thrusters: '6 vectored', 'Degrees of freedom': '6', 'Depth rating': '100 m', 'Maximum speed': '4 knots', Endurance: '60 min', Vision: 'Front + bottom camera', Acoustics: '3 hydrophones' } },
  { name: 'SEA 4.0', image: sea5Detail, tagline: 'Modular predecessor platform', specs: { Thrusters: '6 vectored', 'Degrees of freedom': '6', 'Depth rating': '50 m', 'Maximum speed': '2 knots', Endurance: '60 min', Vision: 'Front + bottom camera', Acoustics: '3 hydrophones' } },
  { name: 'SEA 3.0', image: sea5Pool, tagline: 'Stereo-vision research platform', specs: { Thrusters: '4 rotary', 'Degrees of freedom': '4', 'Depth rating': '50 m', 'Maximum speed': '2 knots', Endurance: '90 min', Vision: 'Stereo vision system' } }
];

function authHeaders(token) { return token ? { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' } : { 'Content-Type': 'application/json' }; }
function Section({ id, title, eyebrow, children }) { return <section id={id} className="section reveal"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>; }

export default function App() {
  const [page, setPage] = useState('home'); const [menu, setMenu] = useState(false);
  const [token, setToken] = useState(() => sessionStorage.getItem('token') || '');
  const [user, setUser] = useState(() => JSON.parse(sessionStorage.getItem('user') || 'null'));
  const navigate = (next) => { setPage(next); setMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const login = (t, u) => { sessionStorage.setItem('token', t); sessionStorage.setItem('user', JSON.stringify(u)); setToken(t); setUser(u); navigate('home'); };
  const logout = () => { sessionStorage.clear(); setToken(''); setUser(null); navigate('home'); };
  useEffect(() => { const observer = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && e.target.classList.add('shown')), { threshold: .08 }); document.querySelectorAll('.reveal').forEach(el => observer.observe(el)); return () => observer.disconnect(); }, [page]);
  const links = [['home','Home'], ['about','About'], ['projects','Vehicles'], ['team','Team'], ['events','Events']];
  return <><header><button className="brand" onClick={() => navigate('home')}><span>◉</span> MTS AUV-ZHCET</button><nav className={menu ? 'open' : ''}>{links.map(([id,label]) => <button className={page===id?'active':''} key={id} onClick={() => navigate(id)}>{label}</button>)}{user && ['member','admin','developer'].includes(user.role) && <button onClick={() => navigate('member')}>Portal</button>}{user && ['admin','developer'].includes(user.role) && <button onClick={() => navigate('admin')}>Admin</button>}{user?.role==='developer' && <button onClick={() => navigate('dev')}>Dev Console</button>}</nav><div className="access">{user ? <><small>{user.role} · {user.username}</small><button className="outline" onClick={logout}>Log out</button></> : <button className="primary" onClick={() => navigate('login')}>Gate access</button>}</div><button className="mobile" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">☰</button></header>
  <main>{page==='home' && <Home navigate={navigate} />}{page==='about' && <About />}{page==='projects' && <Projects />}{page==='team' && <Team />}{page==='events' && <Events />}{page==='login' && <Login login={login} />}{page==='member' && <Member token={token} user={user} />}{page==='admin' && <Admin token={token} user={user} />}{page==='dev' && <Dev token={token} user={user} />}</main><Bot /><footer><span>© {new Date().getFullYear()} MTS AUV-ZHCET</span><span>Main Building, ZHCET, AMU, Aligarh, India · <a href="mailto:auvzhcet@zhcet.ac.in">auvzhcet@zhcet.ac.in</a></span></footer></>;
}

function Home({ navigate }) { const hero = useRef(); const [announcements,setAnnouncements] = useState([]); useEffect(() => { fetch(`${API}/announcements`).then(r=>r.json()).then(setAnnouncements).catch(()=>{}); },[]); const move=e=>{const b=hero.current.getBoundingClientRect(), x=(e.clientX-b.left)/b.width-.5, y=(e.clientY-b.top)/b.height-.5; hero.current.style.setProperty('--x',`${(x+.5)*100}%`); hero.current.style.setProperty('--y',`${(y+.5)*100}%`); hero.current.querySelector('img').style.transform=`rotateX(${-y*8}deg) rotateY(${x*11}deg)`}; return <><section className="hero" ref={hero} onMouseMove={move}><div className="hero-copy"><p className="eyebrow">AUTONOMOUS OCEAN SYSTEMS</p><h1>Built to go<br/><em>below the surface.</em></h1><p>Student-led underwater robotics from ZHCET, Aligarh Muslim University.</p><div><button className="primary" onClick={()=>navigate('projects')}>Explore SEA 5.0</button><button className="text-button" onClick={()=>navigate('about')}>Our mission →</button></div></div><img src={sea5} alt="SEA 5.0 autonomous underwater vehicle" /></section><div className="stats reveal"><div><b>100m</b><span>depth rating</span></div><div><b>6</b><span>vectored thrusters</span></div><div><b>4 knots</b><span>maximum speed</span></div><div><b>60 min</b><span>mission endurance</span></div></div><Section title="Latest signals" eyebrow="CLUB UPDATES"><div className="cards">{announcements.length?announcements.slice(0,3).map(a=><article className="news" key={a.id}><p>{a.type || 'News'} · {a.date}</p><h3>{a.title}</h3><span>{a.content}</span></article>):<article className="news"><p>NEWS</p><h3>Recruitment updates</h3><span>Information will appear here as announcements are published.</span></article>}</div></Section><section className="sponsors"><p>PROUDLY ROOTED AT</p><strong>Mohammad Ali Jauhar University · ZHCET · Marine Technology Society</strong></section></> }
function About(){const [md,setMd]=useState(''); useEffect(()=>{fetch(`${API}/info`).then(r=>r.json()).then(x=>setMd(x.content)).catch(()=>setMd('# MTS AUV-ZHCET\nWe build autonomous and remotely operated underwater vehicles.'))},[]); return <Section title="Mission control" eyebrow="ABOUT THE CLUB"><article className="prose">{md.split('\n').map((line,i)=>line.startsWith('# ')?<h3 key={i}>{line.slice(2)}</h3>:line.startsWith('## ')?<h4 key={i}>{line.slice(3)}</h4>:line?<p key={i}>{line}</p>:null)}</article></Section>}
function Projects(){const [selected,setSelected]=useState(0),[inside,setInside]=useState(false),[drag,setDrag]=useState(0); const v=vehicleData[selected]; return <Section title="Vehicle explorer" eyebrow="SAFINA-E-AABDOZ SERIES"><div className="explorer"><aside>{vehicleData.map((x,i)=><button key={x.name} className={i===selected?'selected':''} onClick={()=>{setSelected(i);setInside(false)}}><img src={x.image} alt=""/><span>{x.name}</span></button>)}</aside><div className={'vehicle-stage '+(inside?'inside':'')} onPointerMove={e=>e.buttons&&setDrag(Math.max(-16,Math.min(16,drag+e.movementX/12)))}><img style={{transform:`rotateY(${drag}deg)`}} src={v.image} alt={v.name}/>{inside&&<div className="parts"><i className="jetson">NVIDIA Jetson</i><i className="thrusters">Vectored thrusters</i><i className="hull">Double-hull frame</i><i className="sensors">Sensors</i><i className="battery">Battery bay</i></div>}<button className="primary inside-button" onClick={()=>setInside(!inside)}>{inside?'Restore outer shell':'Wanna see inside?'}</button></div><article className="specs"><p className="eyebrow">{v.name}</p><h3>{v.tagline}</h3>{Object.entries(v.specs).map(([k,val])=><div key={k}><span>{k}</span><b>{val}</b></div>)}</article></div></Section>}
function Team(){const [members,setMembers]=useState([]); useEffect(()=>fetch(`${API}/members`).then(r=>r.json()).then(setMembers).catch(()=>{}),[]); const fallbacks=[['Software & autonomy','We build the decision layer.'],['Electronics','Power, sensing and embedded systems.'],['Mechanical','Hull design and mission-ready fabrication.']]; const list=members.length?members:fallbacks.map((x,i)=>({id:i,name:x[0],designation:'MTS AUV-ZHCET',one_liner:x[1],course:'ZHCET',branch:'Club division'}));return <Section title="The team behind the dive" eyebrow="PEOPLE"><div className="team-grid">{list.map(m=><article className="flip" key={m.id}><div className="flip-inner"><div className="flip-front" style={m.image?{backgroundImage:`linear-gradient(#07121dcc,#07121dee),url(${m.image})`}:{}}><span>◌</span><h3>{m.name}</h3><p>{m.designation}</p></div><div className="flip-back"><h3>{m.name}</h3><p>{m.one_liner}</p><small>{m.course} · {m.branch}<br/>{m.enrollment_no || m.faculty_no || 'MTS AUV-ZHCET'}</small>{m.email&&<a href={`mailto:${m.email}`}>Email ↗</a>}{m.linkedin&&<a href={m.linkedin} target="_blank">LinkedIn ↗</a>}</div></div></article>)}</div></Section>}
function Events(){const [events,setEvents]=useState([]);useEffect(()=>fetch(`${API}/events`).then(r=>r.json()).then(setEvents).catch(()=>{}),[]);return <Section title="Where we surface" eyebrow="EVENTS & COMPETITIONS"><div className="timeline">{(events.length?events:[{id:1,date:'2026',title:'More events soon',description:'Competition, workshop, and club activity notices will appear here.',location:'ZHCET'}]).map(e=><article key={e.id}><time>{e.date}</time><div><p>{e.category}</p><h3>{e.title}</h3><span>{e.description}</span><small>{e.location}</small></div></article>)}</div></Section>}
function Member({token,user}){const [docs,setDocs]=useState([]);useEffect(()=>{fetch(`${API}/announcements`).then(r=>r.json()).then(setDocs).catch(()=>{})},[]);if(!user||!['member','admin','developer'].includes(user.role))return <Login/>;return <Section title="Member portal" eyebrow="INTERNAL CLUB FILES"><p className="muted">Signed in as <b>{user.username}</b> ({user.role}). The documents below are shared internally with club members.</p><div className="cards">{docs.length?docs.map(d=><article className="news" key={d.id}><p>{d.type || 'Document'} · {d.date}{d.author?` · ${d.author}`:''}</p><h3>{d.title}</h3><span>{d.content}</span></article>):<article className="news"><p>DOCUMENT</p><h3>No files yet</h3><span>Internal announcements and documents will appear here once published by an admin or developer.</span></article>}</div></Section>}
function Login({login}){const [register,setRegister]=useState(false),[data,setData]=useState({username:'',password:'',role:'member'}),[message,setMessage]=useState('');const submit=async e=>{e.preventDefault();const r=await fetch(`${API}/auth/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)return setMessage(out.message);if(register)return setMessage(out.message);login(out.token,out.user)};return <section className="auth"><p className="eyebrow">{register?'REQUEST ACCESS':'MEMBER PORTAL'}</p><h2>{register?'Join the mission':'Gate access'}</h2><form onSubmit={submit}><label>Username<input required value={data.username} onChange={e=>setData({...data,username:e.target.value})}/></label><label>Password<input required type="password" value={data.password} onChange={e=>setData({...data,password:e.target.value})}/></label>{register&&<label>Access level<select value={data.role} onChange={e=>setData({...data,role:e.target.value})}><option value="member">Member</option><option value="developer">Developer (approval required)</option></select></label>}<button className="primary">{register?'Submit request':'Log in'}</button>{message&&<p className="message">{message}</p>}</form><button className="text-button" onClick={()=>{setRegister(!register);setMessage('')}}>{register?'Already a member? Log in':'Need an account? Register'}</button><small>Demo developer: developer / devpass</small></section>}
function Admin({token,user}){const [info,setInfo]=useState(''),[message,setMessage]=useState('');useEffect(()=>fetch(`${API}/info`).then(r=>r.json()).then(x=>setInfo(x.content)),[]);if(!user||!['admin','developer'].includes(user.role))return <Login/>;const save=async()=>{const r=await fetch(`${API}/info`,{method:'POST',headers:authHeaders(token),body:JSON.stringify({content:info})});setMessage((await r.json()).message)};return <Section title="Admin dashboard" eyebrow="CONTENT CONTROL"><div className="admin-panel"><h3>About-page Markdown</h3><textarea value={info} onChange={e=>setInfo(e.target.value)} rows="16"/><button className="primary" onClick={save}>Save Markdown</button>{message&&<p className="message">{message}</p>}<p className="muted">Use the protected API to manage announcements, events, projects, and members. This editor changes the server-hosted About content directly.</p></div></Section>}
function Dev({token,user}){const [pending,setPending]=useState([]),[logs,setLogs]=useState([]),[db,setDb]=useState(null),[search,setSearch]=useState(''); const load=()=>{if(!token)return;fetch(`${API}/dev/pending-users`,{headers:authHeaders(token)}).then(r=>r.json()).then(setPending);fetch(`${API}/dev/timeline`,{headers:authHeaders(token)}).then(r=>r.json()).then(setLogs);fetch(`${API}/dev/database-inspect`,{headers:authHeaders(token)}).then(r=>r.json()).then(setDb)};useEffect(load,[]);if(user?.role!=='developer')return <Login/>;const approve=async id=>{await fetch(`${API}/dev/approve-user`,{method:'POST',headers:authHeaders(token),body:JSON.stringify({id})});load()};return <Section title="Developer console" eyebrow="SYSTEM HEALTH"><div className="dev-grid"><article><h3>Access manager</h3>{pending.length?pending.map(p=><p className="request" key={p.id}>{p.username}<button className="primary" onClick={()=>approve(p.id)}>Approve</button></p>):<p className="muted">No pending developer requests.</p>}</article><article><h3>Environment</h3><p className="muted">API and session limits are verified server-side. Sensitive values are never returned to the browser.</p></article><article className="wide"><h3>Timeline history</h3><input placeholder="Search audit history" value={search} onChange={e=>setSearch(e.target.value)}/>{logs.filter(l=>JSON.stringify(l).toLowerCase().includes(search.toLowerCase())).map(l=><p className="log" key={l.id}><b>{l.action}</b> · {l.username} <small>{new Date(l.timestamp).toLocaleString()}</small><br/>{l.details}</p>)}</article><article className="wide"><h3>Database monitor</h3><pre>{db?JSON.stringify(db,null,2):'Loading database entries…'}</pre></article></div></Section>}
function Bot(){const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[items,setItems]=useState([]);const send=async e=>{e.preventDefault();if(!message.trim())return;const q=message;setItems([...items,{by:'you',text:q}]);setMessage('');try{const r=await fetch(`${API}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,sessionId:sessionStorage.getItem('chatId')||(sessionStorage.setItem('chatId',crypto.randomUUID()),sessionStorage.getItem('chatId'))})});const x=await r.json();setItems(i=>[...i,{by:'bot',text:x.reply||x.message}])}catch{setItems(i=>[...i,{by:'bot',text:'Connection unavailable. Please try again shortly.'}])}};return <div className={'bot '+(open?'open':'')}><button className="bot-toggle" onClick={()=>setOpen(!open)}>{open?'×':'◌ Ask AUV'}</button>{open&&<div className="bot-panel"><b>AUV-ZHCET helper</b><div className="chat">{items.length?items.map((x,i)=><p className={x.by} key={i}>{x.text}</p>):<p className="botmsg">Ask about SEA vehicles, workshops, team, and events.</p>}</div><form onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask the club helper"/><button>↑</button></form></div>}</div>}
